/**
 * Texto legal del contrato (igual al de la plantilla de GHL, oct-2026).
 * Cambia ~1 vez al año: se edita aquí. Cada párrafo admite **negrita**.
 */

export const CLAUSULA_RESPONSABILIDAD = {
  titulo: 'Cláusula de responsabilidad, condiciones generales y penalidades',
  parrafos: [
    '**Agencia:** TRAVEL WORLD COLOMBIA Agencia de Viajes y Turismo, con Registro Nacional de Turismo 27287, se hace responsable ante los usuarios por la totalidad de la prestación de los servicios descritos en sus programas ofrecidos. Actúa como intermediario entre los agentes, operadores y prestadores de servicios turísticos, declinando por lo tanto toda responsabilidad por situaciones de fuerzas de la naturaleza, tales como huracán, maremoto, terremoto, accidentes, huelgas, asonadas, fenómenos climáticos o naturales, pandemias, condiciones de seguridad, factores políticos, negación de permisos de ingreso, asuntos de salubridad y cualquier otro evento de fuerza mayor o caso fortuito, pues los riesgos y peligros del viaje pertenecen exclusivamente al usuario durante el tiempo de viaje. Nos sujetamos al régimen de responsabilidad que establece la Ley 300/96, y los Decretos 107/97 y 63/02. TRAVEL WORLD COLOMBIA Agencia de Viajes y Turismo como organizador pone el precio a los viajes, los mismos pueden ser aceptados o rechazados por el cliente. En caso de confirmación con depósito se entienden aceptadas todas las condiciones, restricciones y penalidades.',
    'La agencia de viajes no asume responsabilidad alguna frente al usuario o viajero por el servicio de transporte aéreo, salvo que se trate de vuelos fletados y de acuerdo con lo especificado en el contrato de transporte. La prestación de tal servicio se rige por las normas legales aplicables al servicio de transporte aéreo. Los eventos tales como retrasos o modificaciones imprevistas en los horarios de los vuelos dispuestos por las aerolíneas, los derechos del usuario y los procedimientos para hacer efectivas las devoluciones de dinero a que estos hechos den lugar, se regirán por las disposiciones legales pertinentes y en particular por las contenidas en el Reglamento Aeronáutico Colombiano (RAC).',
    '**Viajero:** Aplican restricciones y penalidades por cambios o incumplimiento conforme a las normas legales y conforme a la costumbre comercial en turismo. TRAVEL WORLD COLOMBIA Agencia de Viajes y Turismo cancela en su totalidad y con anterioridad todos los servicios ofrecidos en cada uno de sus programas; en ningún caso podrá hacer devolución de dinero, pero en caso de que el pasajero por enfermedad o por razones de fuerza mayor comprobada se vea obligado a retractarse del viaje y se encuentre dentro de los términos legales o las condiciones del plan lo permitan, se tramitará su respectiva cancelación, teniendo en cuenta que esto acarreará un descuento por concepto de gastos administrativos. TRAVEL WORLD COLOMBIA Agencia de Viajes y Turismo hará el trámite de reembolso que tomará un máximo de seis (6) meses o antes según el caso. Se efectuará reembolso solo en caso de fuerza mayor, con soportes debidamente diligenciados y si los operadores finales lo aprueban, ya que no depende de la Agencia el manejo de dinero pagado a los operadores finales. En caso de que el operador final o prestador del servicio determine que el proceso debe hacerlo directamente el usuario del servicio, el viajero acepta que realizará el respectivo trámite directamente y exonera de cualquier responsabilidad a la agencia. Se descontará el porcentaje que por expedición de tiquetes o penalidad cobre la aerolínea, y de acuerdo a la tarifa negociada. Adicionalmente, un 20% por gastos administrativos. Una vez se haya iniciado el viaje no habrá devolución de dinero.',
    'TRAVEL WORLD COLOMBIA Agencia de Viajes y Turismo, como organizador del plan turístico, pone valor al mismo. Para confirmar la reserva de paquetes turísticos se requiere siempre un depósito mínimo del 30% sobre el valor total del viaje o el porcentaje informado por su asesor. Para el caso de tiquetes aéreos es necesario el pago del 100%, excepto si los mismos hacen parte de un bloqueo de grupo. Si el cliente desiste del viaje por motivos personales o por la NO obtención de algún requisito o permiso para el viaje, se aplicarán los porcentajes indemnizatorios sobre el total de la porción terrestre solo si la tarifa lo permite así: más de 30 días antes del viaje el 20%, de 29 a 20 días antes del viaje el 40%, de 19 a 8 días antes del viaje el 60%, menos de 8 días antes del viaje se penalizará con el 100% del valor depositado. Siempre y cuando la tarifa tomada lo permita y dependiendo del destino y operador final. Tiquetes aéreos están sujetos a su clase tarifaria y condiciones de las mismas.',
    'En el evento en que el usuario no se presente o no haga uso de los servicios contratados (NO SHOW) en la fecha y condiciones pactadas, de conformidad con lo previsto en el artículo 65 de la Ley 300 de 1996, la agencia podrá retener la totalidad del valor pactado como anticipo sin que haya lugar a devolución del mismo.',
    'En caso de modificaciones en vuelos realizados por las aerolíneas, el viajero entiende que son potestativas de las mismas dependiendo de su situación y acepta que para cualquier cambio, modificación o reembolso éstos deben ser tramitados directamente con el prestador directo del servicio, entendiendo que dichos cambios no son responsabilidad de la agencia.',
    '**Documentos:** los vouchers y/o documentos serán entregados 8 días previos a la salida del viaje por correo electrónico.',
  ],
}

export const CLAUSULA_DATOS = {
  titulo: 'Cláusula de tratamiento y protección de datos personales',
  parrafos: [
    'En cumplimiento de la **Ley 1581 de 2012, el Decreto 1377 de 2013**, el Decreto 1074 de 2015 y demás normas concordantes, el titular de la reserva autoriza de manera previa, expresa e informada a **VAMOS POR MÁS S.A.S.** y sus establecimientos de comercio **TRAVEL WORLD COLOMBIA y TRAVEL WORLD MAYORISTA**, para recolectar, almacenar, usar, circular, actualizar y suprimir sus datos personales, con la finalidad de gestionar la prestación de los servicios turísticos contratados, incluyendo la realización de reservas, emisión de tiquetes, coordinación con aerolíneas, hoteles, operadores turísticos, asistencias médicas y demás proveedores, así como para fines administrativos, comerciales y legales.',
    'Así mismo, autoriza que sus datos personales puedan ser compartidos con terceros aliados y proveedores, tanto nacionales como internacionales, cuando sea necesario para la correcta ejecución del servicio contratado.',
    'El titular de los datos personales podrá ejercer sus derechos a conocer, actualizar, rectificar y solicitar la supresión de sus datos, así como a revocar la autorización otorgada, conforme a la normatividad vigente, a través de los correos electrónicos: **jefedeservicios.travelworld@gmail.com y contacto@travelworldcolombia.com.**',
    '**VAMOS POR MÁS S.A.S.**, a través de sus establecimientos de comercio **TRAVEL WORLD COLOMBIA y TRAVEL WORLD MAYORISTA**, garantiza la confidencialidad, seguridad y adecuado tratamiento de los datos personales, implementando las medidas necesarias para prevenir su adulteración, pérdida, consulta, uso o acceso no autorizado.',
    'El titular de la reserva autoriza el tratamiento de sus datos personales y, en caso de incluir a otros pasajeros, declara que cuenta con la autorización previa, expresa e informada de dichos titulares para suministrar sus datos personales y permitir su tratamiento conforme a lo establecido en la presente cláusula. En tal sentido, manifiesta que actúa en calidad de autorizado de los demás pasajeros incluidos en la reserva, comprometiéndose a informarles el contenido de esta política y asumiendo cualquier responsabilidad derivada de su incumplimiento.',
  ],
}

export const DECLARACION_FIRMA =
  'Declaro que entiendo y acepto las condiciones de mi tiquete aéreo, la cláusula de responsabilidad y condiciones del presente contrato y autorizo el tratamiento de mis datos personales; para constancia firmo a continuación:'
